backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'sosok'
    label: 'Sosok'
    folder: 'content/sosok'
    create: true
    slug: '{{slug}}'
    media_folder: 'assets/images'
    public_folder: 'assets/images'
    path: '{{id}}'
    editor:
      preview: true
    files:
      - label: 'Terms'
        name: 'terms'
        file: 'content/sosok/terms.md'
        fields:
          - { label: 'Id', name: 'id', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Services', name: 'services', widget: 'string' }
          - { label: 'Categories', name: 'categories', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY.MM.DD' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - label: 'Policy'
        name: 'policy'
        file: 'content/sosok/policy.md'
        fields:
          - { label: 'Id', name: 'id', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Services', name: 'services', widget: 'string' }
          - { label: 'Categories', name: 'categories', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY.MM.DD' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'azit'
    label: 'Azit'
    folder: 'content/azit'
    create: true
    slug: '{{slug}}'
    media_folder: 'assets/images'
    public_folder: 'assets/images'
    path: '{{id}}'
    editor:
      preview: true
   

  - name: 'business'
    label: 'Business'
    folder: 'content/business'
    create: true
    slug: '{{slug}}'
    media_folder: 'assets/images'
    public_folder: 'assets/images'
    path: '{{id}}'
    editor:
      preview: true
    fields:
      - { label: 'Id', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Services', name: 'services', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY.MM.DD' }
      - { label: 'Body', name: 'body', widget: 'markdown' }