backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'helps'
    label: 'Helps'
    folder: 'content/sosok'
    create: true
    slug: 'index'
    media_folder: 'assets/images'
    public_folder: 'assets/images'
    path: '{{services}/{categories}/{title}/index}'
    editor:
      preview: false
    fields:
      - { label: 'Id', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Services', name: 'services', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }